apiVersion: v1
kind: ConfigMap
metadata:
  name: styringsinfo-kvalitetssjekk-soda-config
  namespace: tbd
data:
  config.yaml: |
    data_source spre_styringsinfo_dataset:
      type: bigquery
      connection:
        project_id: tbd-dev-7ff9
        dataset: spre_styringsinfo_dataset
