apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: helse-styringsinfo-kvalitetssjekk-alerts
  namespace: tbd
  labels:
    team: tbd
spec:
  groups:
    - name: helse-styringsinfo-kvalitetssjekk-alerts
      rules:
        - alert: NaisjobFailed
          expr: kube_job_failed{job_name=~"^styringsinfo-kvalitetssjekk.*", namespace="tbd"} > 0
          for: 2m
          annotations:
            consequence: "Naisjob som sjekker BigQuery-data for styringsinformasjon feilet"
            action: "@sp-styringsinfo-bros - Sjekk https://logs.adeo.no/app/r/s/hqwMP"
            summary: |-
              NaisJob helse-styringsinfo-kvalitetssjekk feiler tbd - sjekkene fullføres ikke. 
              Repo: https://github.com/navikt/helse-styringsinfo-kvalitetssjekk
              Alert: https://github.com/navikt/helse-styringsinfo-kvalitetssjekk/blob/main/nais/alerts.yaml
          labels:
            namespace: tbd
            severity: warning
            sykepenger_styringsinfo_type_kvalitetssjekk: dev-alert
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sykepenger-styringsinfo-dev-slack-kvalitetssjekk
  namespace: tbd
  labels:
    team: tbd
    alertmanagerConfig: sykepenger-styringsinfo-dev-slack-kvalitetssjekk
spec:
  receivers:
    - name: sykepenger-styringsinfo-dev-receiver-kvalitetssjekk
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#sykepenger-styringsinfo-dev'
          iconEmoji: ':alert:'
          username: 'Alert dev-gcp'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sykepenger_styringsinfo_type_kvalitetssjekk"
        matchType: "="
        value: "dev-alert"
    groupInterval: 10s
    groupWait: 5s
    receiver: sykepenger-styringsinfo-dev-receiver-kvalitetssjekk
    repeatInterval: 25h