apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: styringsinfo-kvalitetssjekk
  namespace: tbd
spec:
  image: ghcr.io/navikt/nada-soda:2023-06-12-ac65194 # TODO: Vurder å bruke en tag som ikke er knyttet til en commit?
  accessPolicy:
    outbound:
      rules:
        - application: nada-soda
          namespace: nada
  env:
    - name: SODA_CONFIG
      value: /var/run/configmaps/soda-config/config.yaml
    - name: SODA_CHECKS_FOLDER
      value: /var/run/configmaps/soda-checks
    - name: SLACK_CHANNEL
      value: "#sykepenger-styringsinfo-data"
  schedule: '09 11 * * *' # TODO: Vurder å kjøre oftere? (enn kl 09:11 hver dag)
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 1
  concurrencyPolicy: Forbid
  filesFrom:
    - configmap: soda-checks
    - configmap: soda-config
  gcp:
    permissions:
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: tbd-prod-eacd
      role: roles/bigquery.readSessionUser
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: tbd-prod-eacd
      role: roles/bigquery.dataViewer
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: tbd-prod-eacd
      role: roles/bigquery.jobUser
