apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: tbd
data:
  spre_styringsinfo_dataset.yaml: |
    checks for public_vedtak_forkastet:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"
      - freshness(forkastet_tidspunkt) < 2d:
          name: "Vi har ikke sett noen vedtak bli forkastet de siste to døgn"
    
    checks for public_vedtak_dokument_mapping:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"

  styringsinfo_dataset.yaml: |
    checks for styringsinfo_sendt_soknad_view:
      - row_count > 0:
          name: "Sjekk for evt tomt view"
      - freshness(soknad_mottatt) < 1d:
          name: "Vi har ikke mottatt noen søknader det siste døgnet"
    
    checks for styringsinfo_vedtak_fattet_view:
      - row_count > 0:
          name: "Sjekk for evt tomt view"
      - freshness(vedtak_fattet) < 2d:
          name: "Vi har ikke sett noen fattede vedtak de siste to døgn"
