apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config
  namespace: tbd
data:
  config.yaml: |
    data_source spre_styringsinfo_dataset:
      type: bigquery
      connection:
        project_id: {{ gcp.project }}
        dataset: spre_styringsinfo_dataset
    data_source styringsinfo_dataset:
      type: bigquery
      connection:
        project_id: {{ gcp.project }}
        dataset: styringsinfo_dataset
