apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: tbd
data:
  spre_styringsinfo_dataset.yaml: |
    checks for public_sendt_soknad:
    - row_count > 0:
        name: "Sjekk for evt tom tabell"
    - freshness(sendt) < 1d:
        name: "Har noe blitt vedtatt siste døgn?"

    checks for public_vedtak_fattet:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"
      - freshness(vedtak_fattet_tidspunkt) < 1d:
          name: "Har noe blitt vedtatt siste døgn?"
    
    checks for public_vedtak_forkastet:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"
      - freshness(forkastet_tidspunkt) < 1d:
          name: "Har noe blitt forkastet siste døgn?"
    
    checks for public_vedtak_dokument_mapping:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"

  styringsinfo_dataset.yaml: |
    checks for styringsinfo_sendt_soknad_view:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"
    
    checks for styringsinfo_vedtak_fattet_view:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"