apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: tbd
data:
  spre_styringsinfo_dataset.yaml: |
    checks for public_vedtak_forkastet:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"
      - freshness(forkastet_tidspunkt) < 1d:
          name: "Vi har ikke sett noen vedtak bli forkastet det siste døgnet"
    
    checks for public_vedtak_dokument_mapping:
      - row_count > 0:
          name: "Sjekk for evt tom tabell"

  styringsinfo_dataset.yaml: |
    checks for styringsinfo_sendt_soknad_view:
      - row_count > 0:
          name: "Sjekk for evt tomt view"
      - freshness(soknad_mottatt) < 1d:
          name: "Vi har ikke mottatt noen søknader det siste døgnet"
    
    checks for styringsinfo_vedtak_fattet_view:
      - row_count > 0:
          name: "Sjekk for evt tomt view"
      - freshness(vedtak_fattet) < 1d:
          name: "Vi har ikke sett noen fattede vedtak det siste døgnet"

    checks for styringsinfo_datakvalitet_soknadhendelser_view:
      - max(diff_soknadhendelser) <= 5:
          name: "Diff i antall søknadshendelser mellom Flex og styringsinfo *for forrige hele døgn* viser flere søknadshendelser i Flex enn i styringsinfo og mer enn det vi tror skyldes kode 6 (vi aksepterer en diff på 5)"

      - min(diff_soknadhendelser) >= 0:
          name: "Diff i antall søknadshendelser mellom Flex og styringsinfo *for forrige hele døgn* viser flere søknadshendelser i styringsinfo enn i Flex - dette er ikke forventet"
