apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks-prod
  namespace: tbd
data:
  styringsinfo_dataset.yaml: |
    checks for styringsinfo_sendt_soknad_view:
      - row_count > 0:
          name: "Sjekk for evt tomt view"
      - freshness(soknad_mottatt) < 1d:
          name: "Vi har ikke mottatt noen søknader det siste døgnet"
    
    checks for styringsinfo_vedtak_fattet_view:
      - row_count > 0:
          name: "Sjekk for evt tomt view"
      - freshness(vedtak_fattet) < 1d:
          name: "Vi har ikke sett noen fattede vedtak det siste døgnet"

    checks for styringsinfo_datakvalitet_soknadhendelser_view:
      - max(diff_soknadhendelser) <= 5:
          name: "Diff i antall søknadshendelser mellom Flex og styringsinfo er liten nok til å skyldes kode 6"

      - min(diff_soknadhendelser) >= 0:
          name: "Diff i antall søknadshendelser mellom Flex og styringsinfo viser flere søknadshendelser i styringsinfo enn i Flex - dette er ikke forventet"
