name: build, push and deploy
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'local/'
      - 'nais/alerts.yaml'
      - '.github/workflows/alerts.yaml'

jobs:
  deployDevRunOnce:
    name: deploy to dev to run once
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-dev.yaml,nais/naisjob.yaml
          VARS: nais/dev-run-once.yaml

  deployDevRunOnSchedule:
    name: deploy to dev run on schedule
    needs: [deployDevRunOnce]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-dev.yaml,nais/naisjob.yaml
          VARS: nais/dev.yaml

  deployProRunOnce:
    name: deploy to prod run once
    needs: [deployDevRunOnce]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy prod-gcp run once
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-prod.yaml,nais/naisjob.yaml
          VARS: nais/prod-run-once.yaml

  deployProRunOnSchedule:
    name: deploy to prod run on schedule
    needs: [deployProRunOnce]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy prod-gcp run on schedule
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-prod.yaml,nais/naisjob.yaml
          VARS: nais/prod.yaml
