name: build, push and deploy
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'local/'
      - 'nais/alerts.yml'
      - '.github/workflows/alerts.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Deploy dev-gcp run once
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-dev.yaml,nais/naisjob.yaml
          VARS: nais/dev-run-once.yaml

      - name: Deploy dev-gcp run on schedule
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-dev.yaml,nais/naisjob.yaml
          VARS: nais/dev.yaml

      - name: Deploy prod-gcp run once
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-prod.yaml,nais/naisjob.yaml
          VARS: nais/prod-run-once.yaml

      - name: Deploy prod-gcp run on schedule
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/soda-config.yaml,nais/soda-checks-prod.yaml,nais/naisjob.yaml
          VARS: nais/prod.yaml
